#!/usr/bin/env bash
# Cross-compile TinyCC (libtcc.a) for Android aarch64
#
# Usage: ./scripts/build-tinycc.sh
#
# Bun uses TinyCC for its built-in C compiler. We need to cross-compile
# libtcc.a as a static library for Android aarch64.
#
# Source: oven-sh/tinycc (Bun's fork of TinyCC)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../ci/scripts/env.sh"

TINYCC_COMMIT="${TINYCC_COMMIT:-b91835d8701523e895a2b447713630069514e291}"
TINYCC_SRC="${WORK_DIR}/tinycc-src"
TINYCC_BUILD="${TINYCC_SRC}/build-android"

incremental_exec tinycc \
    --input "$SCRIPT_DIR/build-tinycc.sh" --input "$REPO_ROOT/ci/scripts/env.sh" --input "$TINYCC_SRC" \
    --value "TINYCC_COMMIT=$TINYCC_COMMIT" --value "ANDROID_API=$ANDROID_API" \
    --dep "$BUN_STATE_DIR/nodes/webkit.json" \
    --output "$WEBKIT_OUTPUT/lib/libtcc.a"

echo "=== Building TinyCC (libtcc.a) for Android aarch64 ==="

# Check if already built and installed. The state wrapper exits before this
# body on a validated hit; on a miss we must keep the objects and allow the
# changed source/configuration to rebuild incrementally.
if [ "${BUILD_STATE_MISS:-0}" != "1" ] && [ -f "$WEBKIT_OUTPUT/lib/libtcc.a" ]; then
    echo ">>> libtcc.a already exists at $WEBKIT_OUTPUT/lib/libtcc.a"
    ls -la "$WEBKIT_OUTPUT/lib/libtcc.a"
    exit 0
fi

# Clone TinyCC source
if [ ! -d "$TINYCC_SRC/.git" ]; then
    echo ">>> Cloning TinyCC at commit ${TINYCC_COMMIT}..."
    mkdir -p "$TINYCC_SRC"
    cd "$TINYCC_SRC"
    git init
    git remote add origin https://github.com/oven-sh/tinycc.git
    git fetch --depth=1 origin "${TINYCC_COMMIT}"
    git checkout FETCH_HEAD
else
    current="$(git -C "$TINYCC_SRC" rev-parse HEAD 2>/dev/null || true)"
    if [ "$current" != "$TINYCC_COMMIT" ]; then
        if [ -n "$(git -C "$TINYCC_SRC" status --porcelain --untracked-files=all)" ]; then
            echo "ERROR: TinyCC checkout is at $current, expected $TINYCC_COMMIT, and has local changes." >&2
            echo "       Refusing to reset it; preserve or remove the checkout explicitly." >&2
            exit 1
        fi
        echo ">>> Updating TinyCC source to ${TINYCC_COMMIT}..."
        git -C "$TINYCC_SRC" fetch --depth=1 origin "${TINYCC_COMMIT}"
        git -C "$TINYCC_SRC" checkout --detach -q FETCH_HEAD
    else
        echo ">>> TinyCC source already exists at $TINYCC_SRC"
    fi
fi

# Build libtcc.a without discarding objects from a previous runner. TinyCC is
# small enough for a timestamp scan; this keeps each translation unit that is
# still current and recreates only the archive when an object changed.
echo ">>> Compiling TinyCC for Android aarch64..."
mkdir -p "$TINYCC_BUILD"

SOURCES=(
    libtcc.c
    tccpp.c
    tccgen.c
    tccelf.c
    tccasm.c
    tccrun.c
    arm64-gen.c
    arm64-link.c
    arm-asm.c
)

cd "$TINYCC_SRC"

CC=("$ANDROID_CC")
if command -v ccache >/dev/null 2>&1; then
    CC=(ccache "$ANDROID_CC")
fi

# Keep a per-object compile signature. The state wrapper deliberately marks a
# node dirty when its dependency manifest changes, but that does not mean the
# TinyCC translation units need recompilation. Conversely, a changed compiler
# flag/configuration must never leave an old object looking reusable. Depfiles
# give us the real header dependency set, including headers outside include/.
COMPILER_VERSION="$("$ANDROID_CC" --version 2>/dev/null | sed -n '1p' || true)"

# Create minimal config.h (normally generated by ./configure), but do not
# touch its mtime on every retry or all objects would look stale.
if [ ! -f "$TINYCC_SRC/config.h" ] || ! grep -qF '#define TCC_TARGET_ARM64 1' "$TINYCC_SRC/config.h"; then
cat > "$TINYCC_SRC/config.h" <<'CONFEOF'
#define TCC_VERSION "0.9.27"
#define TCC_TARGET_ARM64 1
#define CONFIG_TCC_CROSSPREFIX ""
#define CONFIG_TCCDIR "/data/data/com.termux/files/usr/lib/tcc"
CONFEOF
fi

ARCHIVE_DIRTY=0

CONFIG_DIGEST="$(sha256sum "$TINYCC_SRC/config.h" | cut -d' ' -f1)"
COMPILE_SIGNATURE="$(printf '%s\n' \
    "$TINYCC_COMMIT" "$ANDROID_API" "$ANDROID_NDK_VERSION" \
    "$ANDROID_CC" "$COMPILER_VERSION" "$CONFIG_DIGEST" \
    '-O2 -fPIC -Wall -fno-strict-aliasing -DONE_SOURCE=0 -DTCC_TARGET_ARM64' \
    | sha256sum | cut -d' ' -f1)"

for src in "${SOURCES[@]}"; do
    obj="$TINYCC_BUILD/${src%.c}.o"
    depfile="$obj.d"
    signature_file="$obj.signature"
    needs_compile=0
    if [ ! -s "$obj" ] || [ ! -s "$depfile" ] || [ ! -s "$signature_file" ] \
        || [ "$(cat "$signature_file" 2>/dev/null || true)" != "$COMPILE_SIGNATURE" ]; then
        needs_compile=1
    else
        # The depfile is a make rule. Let make evaluate escaped paths and
        # transitive headers instead of trying to parse C preprocessor syntax.
        if ! make -q -f "$depfile" >/dev/null 2>&1; then
            needs_compile=1
        fi
    fi
    if [ "$needs_compile" = "1" ]; then
        echo "  Compiling $src..."
        "${CC[@]}" \
            -O2 -fPIC -Wall -fno-strict-aliasing \
            -DONE_SOURCE=0 \
            '-DTCC_LIBTCC1="\0"' \
            '-DTCC_VERSION="0.9.27"' \
            -DTCC_TARGET_ARM64 \
            -I"$TINYCC_SRC" \
            -I"$TINYCC_SRC/include" \
            -c "$src" \
            -MMD -MF "$depfile" \
            -o "$obj"
        printf '%s\n' "$COMPILE_SIGNATURE" > "$signature_file"
        ARCHIVE_DIRTY=1
    else
        echo "  Reusing $src"
    fi
done

if [ "$ARCHIVE_DIRTY" = "1" ] || [ ! -s "$TINYCC_BUILD/libtcc.a" ]; then
    echo ">>> Creating libtcc.a..."
    "$ANDROID_AR" rcs "$TINYCC_BUILD/libtcc.a" "$TINYCC_BUILD"/*.o
else
    echo ">>> Reusing libtcc.a"
fi

# Install to webkit-android output (where Bun's CMake expects it)
mkdir -p "$WEBKIT_OUTPUT/lib"
cp "$TINYCC_BUILD/libtcc.a" "$WEBKIT_OUTPUT/lib/"

echo ""
echo "=== TinyCC build complete ==="
echo "Library: $WEBKIT_OUTPUT/lib/libtcc.a"
ls -la "$WEBKIT_OUTPUT/lib/libtcc.a"
file "$WEBKIT_OUTPUT/lib/libtcc.a"
