#!/usr/bin/env bun
/**
 * Build OpenCode for Android (aarch64)
 *
 * This script:
 * 1. Generates the models-snapshot.js
 * 2. Loads migrations
 * 3. Creates a plugin wrapper for the CLI
 * 4. Bundles OpenCode for the HOST platform using CLI:
 *      bun build --compile ... → opencode-host (x86_64 standalone)
 * 5. Extracts the module graph from the host binary
 * 6. Appends it raw to the Android Bun binary (no ELF modification)
 *
 * The raw append approach is used because --compile-executable-path
 * modifies the ELF (adds a .bun section) which causes SIGTRAP on
 * Android due to ELF structure incompatibility.
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"

// These are set by the build-opencode.sh wrapper script
const OPENCODE_DIR = process.env.OPENCODE_DIR || (() => { throw new Error("OPENCODE_DIR env var not set") })()
const ANDROID_BUN = process.env.ANDROID_BUN || (() => { throw new Error("ANDROID_BUN env var not set") })()
const OUTPUT_DIR = process.env.OUTPUT_DIR || (() => { throw new Error("OUTPUT_DIR env var not set") })()

// Validate Android bun exists
if (!fs.existsSync(ANDROID_BUN)) {
  console.error("Android bun binary not found at:", ANDROID_BUN)
  process.exit(1)
}

const opencodePkgDir = path.join(OPENCODE_DIR, "packages/opencode")
process.chdir(opencodePkgDir)

const VERSION = process.env.OPENCODE_VERSION || "1.3.13"
const CHANNEL = process.env.OPENCODE_CHANNEL || "latest"

console.log(`Building OpenCode v${VERSION} (channel: ${CHANNEL}) for Android aarch64`)

// ────────────────────────────────────────────────────────────────
// Step 1: Generate models-snapshot.js
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 1: Generating models-snapshot.js ===")
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
let modelsData: string = ""
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else {
  console.log(`Fetching from ${modelsUrl}/api.json ...`)
  let fetchErr: Error | null = null
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const resp = await fetch(`${modelsUrl}/api.json`, { signal: AbortSignal.timeout(15000) })
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
      modelsData = await resp.text()
      fetchErr = null
      break
    } catch (err: any) {
      fetchErr = err
      console.error(`  Attempt ${attempt}/3 failed: ${err.message}`)
      if (attempt < 3) await new Promise(r => setTimeout(r, 2000 * attempt))
    }
  }
  if (fetchErr) {
    console.error(`ERROR: Failed to fetch models after 3 attempts: ${fetchErr.message}`)
    process.exit(1)
  }
}
await Bun.write(
  path.join(opencodePkgDir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(opencodePkgDir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// ────────────────────────────────────────────────────────────────
// Step 2: Load migrations
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 2: Loading migrations ===")
const migrationDirs = (
  await fs.promises.readdir(path.join(OPENCODE_DIR, "packages/opencode/migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(OPENCODE_DIR, "packages/opencode/migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// ────────────────────────────────────────────────────────────────
// Step 3: Write plugin wrapper for CLI
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 3: Creating plugin wrapper ===")

let parserWorkerResolved: string
try {
  parserWorkerResolved = require.resolve("@opentui/core/parser.worker")
} catch {
  parserWorkerResolved = path.resolve(OPENCODE_DIR, "node_modules/@opentui/core/src/lib/tree-sitter/parser.worker.ts")
}
console.log(`Parser worker: ${parserWorkerResolved}`)

const workerPath = "./src/cli/tui/worker.ts"
const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(OPENCODE_DIR, parserWorkerResolved).replaceAll("\\", "/")

// Create a temporary plugin file that the CLI --plugin flag can load.
const pluginFileName = ".build-solid-plugin.ts"
const pluginPath = path.join(opencodePkgDir, pluginFileName)
const pluginContent = `import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"
const _plugin = createSolidTransformPlugin()
export default _plugin
`
await Bun.write(pluginPath, pluginContent)
console.log(`Plugin wrapper written: ${pluginPath}`)

// ────────────────────────────────────────────────────────────────
// Step 4: Bundle for HOST platform using CLI
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 4: Bundling OpenCode for HOST platform ===")

await $`rm -rf ${OUTPUT_DIR}`
await $`mkdir -p ${OUTPUT_DIR}`

const hostBinaryPath = path.join(OUTPUT_DIR, "opencode-host")
const migrationsJson = JSON.stringify(migrations)
const parserWorkerPath = bunfsRoot + workerRelativePath

console.log("Running: bun build --compile ... --> opencode-host (x86_64)")

const buildArgs = [
  "bun", "build", "--compile",
  `--plugin=${pluginFileName}`,
  "--conditions=browser",
  `--tsconfig=./tsconfig.json`,
  `--outfile=${hostBinaryPath}`,
  `--define=OPENCODE_VERSION=${JSON.stringify(VERSION)}`,
  `--define=OPENCODE_MIGRATIONS=${migrationsJson}`,
  `--define=OTUI_TREE_SITTER_WORKER_PATH=${JSON.stringify(parserWorkerPath)}`,
  `--define=OPENCODE_WORKER_PATH=${JSON.stringify(workerPath)}`,
  `--define=OPENCODE_CHANNEL=${JSON.stringify(CHANNEL)}`,
  `--define=OPENCODE_LIBC=${JSON.stringify("")}`,
  "./src/index.ts",
  parserWorkerResolved,
  workerPath,
]

const proc = Bun.spawnSync(buildArgs, {
  cwd: opencodePkgDir,
  stdio: ["inherit", "inherit", "inherit"],
})

if (proc.exitCode !== 0) {
  console.error(`Build failed with exit code ${proc.exitCode}`)
  process.exit(proc.exitCode ?? 1)
}

// ────────────────────────────────────────────────────────────────
// Step 5: Extract module graph from host binary
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 5: Extracting module graph ===")

const hostFileBytes = new Uint8Array(await Bun.file(hostBinaryPath).arrayBuffer())

// Bun 1.3.14+ stores the module graph in an ELF section named ".bun".
// The section content layout is:
//   [total_byte_count as u64 LE (8 bytes)]
//   [string data] [module list] [offsets (32 bytes)]
//   [trailer "\n---- Bun! ----\n" (16 bytes)]
//
// We read the ELF section headers to find .bun, then use the rest
// of the section (after the leading u64) as the module graph for
// the raw-append Android binary.

const TRAILER_STR = "\n---- Bun! ----\n"
const TRAILER_LEN = TRAILER_STR.length  // 16
const OFFSETS_SIZE = 32

// ELF64 header offsets
const e_shoff = Number(new DataView(hostFileBytes.buffer, 0x28, 8).getBigUint64(0, true))
const e_shentsize = new DataView(hostFileBytes.buffer, 0x3A, 2).getUint16(0, true)
const e_shnum = new DataView(hostFileBytes.buffer, 0x3C, 2).getUint16(0, true)
const e_shstrndx = new DataView(hostFileBytes.buffer, 0x3E, 2).getUint16(0, true)

// Read section name string table
const shstrtabEntryOff = e_shoff + e_shstrndx * e_shentsize
const shstrtabOffset = Number(new DataView(hostFileBytes.buffer, shstrtabEntryOff + 0x18, 8).getBigUint64(0, true))
const shstrtabSize = Number(new DataView(hostFileBytes.buffer, shstrtabEntryOff + 0x20, 8).getBigUint64(0, true))
const shstrtab = new Uint8Array(hostFileBytes.buffer, shstrtabOffset, shstrtabSize)
const utf8decoder = new TextDecoder()

// Scan section headers for ".bun"
let bunSectionOffset = 0
let bunSectionSize = 0
for (let i = 0; i < e_shnum; i++) {
  const entryOff = e_shoff + i * e_shentsize
  const nameIdx = new DataView(hostFileBytes.buffer, entryOff, 4).getUint32(0, true)
  // Read null-terminated name from string table
  let nameEnd = nameIdx
  while (nameEnd < shstrtabSize && shstrtab[nameEnd] !== 0) nameEnd++
  const name = utf8decoder.decode(shstrtab.slice(nameIdx, nameEnd))
  if (name === ".bun") {
    bunSectionOffset = Number(new DataView(hostFileBytes.buffer, entryOff + 0x18, 8).getBigUint64(0, true))
    bunSectionSize = Number(new DataView(hostFileBytes.buffer, entryOff + 0x20, 8).getBigUint64(0, true))
    break
  }
}

if (bunSectionSize === 0) {
  console.error("ERROR: .bun section not found in host binary")
  process.exit(1)
}

// Read .bun section content
const bunSectionBytes = hostFileBytes.slice(bunSectionOffset, bunSectionOffset + bunSectionSize)
console.log(`Host binary: ${hostFileBytes.length} bytes`)
console.log(`.bun section: offset=0x${bunSectionOffset.toString(16)}, size=${bunSectionBytes.length} bytes`)

// The .bun section starts with total_byte_count (u64), skip it
const moduleGraphBytes = bunSectionBytes.subarray(8)
console.log(`Module graph extracted: ${moduleGraphBytes.length} bytes`)

// Verify the trailer is present at the right position
const searchBuf = Buffer.from(moduleGraphBytes.buffer, moduleGraphBytes.byteOffset, moduleGraphBytes.length)
const trailerBuf = Buffer.from(TRAILER_STR)
const expectedTrailerStart = moduleGraphBytes.length - TRAILER_LEN
const foundTrailer = searchBuf.compare(trailerBuf, 0, TRAILER_LEN, expectedTrailerStart, moduleGraphBytes.length) === 0
if (!foundTrailer) {
  console.error("ERROR: Module graph trailer not found in .bun section")
  process.exit(1)
}

// Parse module graph offsets for patching
const mgBuf = Buffer.from(moduleGraphBytes)
const mgTrailerBuf = Buffer.from(TRAILER_STR)
const trailerPosInMg = mgBuf.lastIndexOf(mgTrailerBuf)
if (trailerPosInMg < 0) throw new Error("Trailer not found in module graph!")

const mgOffsetsStart = trailerPosInMg - OFFSETS_SIZE
const modOff = mgBuf.readUInt32LE(mgOffsetsStart + 8)
console.log(`String data region: [0, ${modOff})`)

// ────────────────────────────────────────────────────────────────
// Step 5b: Patch undici reference (Bun 1.3.14 built-in module)
// In Bun 1.3.14, undici is a built-in module at
// "builtin://thirdparty/undici". The host bun generates references
// that may not work on Android bun. We need to find and fix them.
//
// Old pattern (Bun <=1.2.x): __reExport(exports_Undici, undici)
// New pattern (Bun 1.3.x):  __require("undici")
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 5b: Patching module graph ===")

const undiciPatterns = [
  {
    name: "old pattern (undici global ref)",
    search: Buffer.from('__reExport(exports_Undici, undici)'),
    replace: Buffer.from('__reExport(exports_Undici, Undici)'),
  },
]

// For Bun 1.3.14, scan the binary for any undici references in the
// module graph string data region [0, modOff)
let totalPatches = 0
for (const pattern of undiciPatterns) {
  if (pattern.search.length !== pattern.replace.length) {
    console.warn(`  SKIP ${pattern.name}: different lengths (${pattern.search.length} vs ${pattern.replace.length})`)
    continue
  }
  const strDataRegion = mgBuf.slice(0, modOff)
  let searchPos = 0
  let count = 0
  while (true) {
    const pos = strDataRegion.indexOf(pattern.search, searchPos)
    if (pos < 0) break
    pattern.replace.copy(mgBuf, pos)
    count++
    totalPatches++
    searchPos = pos + pattern.search.length
  }
  if (count > 0) {
    console.log(`  ✓ ${pattern.name}: patched ${count} occurrence(s)`)
  }
}

if (totalPatches === 0) {
  console.log("  No undici patterns found in module graph (Bun 1.3.14 may have fixed this)")
  console.log("  Scanning for alternative undici patterns...")

  // Search for any undici-related strings in the module graph
  const searchPatterns = [
    Buffer.from('"undici"'),
    Buffer.from("'undici'"),
    Buffer.from('undici'),
    Buffer.from('Undici'),
  ]
  for (const sp of searchPatterns) {
    let pos = 0
    let count = 0
    while (true) {
      pos = mgBuf.indexOf(sp, pos)
      if (pos < 0) break
      if (count < 5) {
        const ctxStart = Math.max(0, pos - 30)
        const ctxEnd = Math.min(mgBuf.length, pos + sp.length + 30)
        console.log(`    Found at offset ${pos}: ${mgBuf.slice(ctxStart, ctxEnd).toString()}`)
      }
      count++
      pos++
    }
    if (count > 0) {
      console.log(`    Pattern "${sp.toString()}": ${count} occurrences`)
    }
  }
}

// ────────────────────────────────────────────────────────────────
// Step 6: Create Android standalone binary (raw append)
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 6: Creating Android standalone binary ===")

// Take the patched module graph and append it raw to the Android Bun binary.
// This is the same approach as the original working code — raw append,
// no ELF modification.
var finalModuleGraph = mgBuf.slice(0, trailerPosInMg + mgTrailerBuf.length)

const androidBunBytes = new Uint8Array(await Bun.file(ANDROID_BUN).arrayBuffer())
const androidBunSize = androidBunBytes.length
console.log(`Android bun size: ${androidBunSize}`)

// New total_byte_count = android_bun_size + module_graph.length + 8
const newTotalByteCount = androidBunSize + finalModuleGraph.length + 8

// Create the output buffer
const outputSize = androidBunSize + finalModuleGraph.length + 8
const output = new Uint8Array(outputSize)

// Copy Android bun binary
output.set(androidBunBytes, 0)

// Copy patched module graph
output.set(new Uint8Array(finalModuleGraph.buffer, finalModuleGraph.byteOffset, finalModuleGraph.length), androidBunSize)

// Write new total_byte_count as u64 LE
const totalView = new DataView(output.buffer, outputSize - 8, 8)
totalView.setUint32(0, newTotalByteCount & 0xFFFFFFFF, true)
totalView.setUint32(4, Math.floor(newTotalByteCount / 0x100000000), true)

const androidOutputPath = path.join(OUTPUT_DIR, "opencode")
await Bun.write(androidOutputPath, output)
fs.chmodSync(androidOutputPath, 0o755)

console.log(`\nAndroid standalone binary: ${androidOutputPath}`)
console.log(`Size: ${(outputSize / 1024 / 1024).toFixed(1)} MB`)

// ────────────────────────────────────────────────────────────────
// Step 7: Verify the binary
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 7: Verifying binary ===")

const verifyBytes = new Uint8Array(await Bun.file(androidOutputPath).arrayBuffer())
const verifyView = new DataView(verifyBytes.buffer, verifyBytes.length - 8, 8)
const verifyTotal = verifyView.getUint32(0, true) + verifyView.getUint32(4, true) * 0x100000000
console.log(`Verification: total_byte_count=${verifyTotal}, file_size=${verifyBytes.length}, match=${verifyTotal === verifyBytes.length}`)

// Check ELF header
const elfMagic = String.fromCharCode(verifyBytes[0], verifyBytes[1], verifyBytes[2], verifyBytes[3])
console.log(`ELF magic: ${elfMagic === "\x7fELF" ? "OK" : "INVALID"}`)

// Check machine type (0xB7 = AArch64)
const machine = verifyBytes[18] | (verifyBytes[19] << 8)
if (machine !== 0xB7) {
  console.error(`ERROR: Expected AArch64 (0xB7), got ${machine === 0x3E ? "x86_64" : `0x${machine.toString(16)}`}`)
  process.exit(1)
}
console.log("Architecture: AArch64 OK")

// ────────────────────────────────────────────────────────────────
// Step 8: Cleanup
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 8: Cleanup ===")
try {
  await $`rm -f ${pluginPath}`
  console.log("Plugin wrapper removed")
} catch {
  // non-fatal
}

console.log("\n=== Build complete! ===")
console.log(`Output: ${androidOutputPath}`)
