#!/usr/bin/env bun
/**
 * Build OpenCode for Android (aarch64)
 *
 * This script:
 * 1. Generates the models-snapshot.js
 * 2. Loads migrations
 * 3. Creates a plugin wrapper for the CLI
 * 4. Cross-compiles OpenCode using:
 *      bun build --compile --compile-executable-path=<android-bun> --target=bun-linux-arm64-android
 *    This tells Bun to use our custom Android Bun binary as the runtime
 *    instead of extracting the module graph manually and concatenating.
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"

// These are set by the build-opencode.sh wrapper script
const OPENCODE_DIR = process.env.OPENCODE_DIR || (() => { throw new Error("OPENCODE_DIR env var not set") })()
const ANDROID_BUN = process.env.ANDROID_BUN || (() => { throw new Error("ANDROID_BUN env var not set") })()
const OUTPUT_DIR = process.env.OUTPUT_DIR || (() => { throw new Error("OUTPUT_DIR env var not set") })()

// Validate Android bun exists
if (!fs.existsSync(ANDROID_BUN)) {
  console.error("Android bun binary not found at:", ANDROID_BUN)
  process.exit(1)
}

const opencodePkgDir = path.join(OPENCODE_DIR, "packages/opencode")
process.chdir(opencodePkgDir)

const VERSION = process.env.OPENCODE_VERSION || "1.3.13"
const CHANNEL = process.env.OPENCODE_CHANNEL || "latest"

console.log(`Building OpenCode v${VERSION} (channel: ${CHANNEL}) for Android aarch64`)

// ────────────────────────────────────────────────────────────────
// Step 1: Generate models-snapshot.js
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 1: Generating models-snapshot.js ===")
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
let modelsData: string = ""
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else {
  console.log(`Fetching from ${modelsUrl}/api.json ...`)
  let fetchErr: Error | null = null
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const resp = await fetch(`${modelsUrl}/api.json`, { signal: AbortSignal.timeout(15000) })
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
      modelsData = await resp.text()
      fetchErr = null
      break
    } catch (err: any) {
      fetchErr = err
      console.error(`  Attempt ${attempt}/3 failed: ${err.message}`)
      if (attempt < 3) await new Promise(r => setTimeout(r, 2000 * attempt))
    }
  }
  if (fetchErr) {
    console.error(`ERROR: Failed to fetch models after 3 attempts: ${fetchErr.message}`)
    process.exit(1)
  }
}
await Bun.write(
  path.join(opencodePkgDir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(opencodePkgDir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// ────────────────────────────────────────────────────────────────
// Step 2: Load migrations
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 2: Loading migrations ===")
const migrationDirs = (
  await fs.promises.readdir(path.join(OPENCODE_DIR, "packages/opencode/migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(OPENCODE_DIR, "packages/opencode/migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// ────────────────────────────────────────────────────────────────
// Step 3: Write plugin wrapper for CLI (Bun.build API doesn't expose
// --compile-executable-path, so we use the CLI instead)
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 3: Creating plugin wrapper ===")

let parserWorkerResolved: string
try {
  parserWorkerResolved = require.resolve("@opentui/core/parser.worker")
} catch {
  parserWorkerResolved = path.resolve(OPENCODE_DIR, "node_modules/@opentui/core/src/lib/tree-sitter/parser.worker.ts")
}
console.log(`Parser worker: ${parserWorkerResolved}`)

const workerPath = "./src/cli/tui/worker.ts"
const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(OPENCODE_DIR, parserWorkerResolved).replaceAll("\\", "/")

// Create a temporary plugin file that the CLI --plugin flag can load.
// Bun's CLI resolves plugins relative to CWD, so we put it inside the
// opencode package directory where @opentui/solid is resolvable.
const pluginFileName = ".build-solid-plugin.ts"
const pluginPath = path.join(opencodePkgDir, pluginFileName)
const pluginContent = `import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"
const _plugin = createSolidTransformPlugin()
export default _plugin
`
await Bun.write(pluginPath, pluginContent)
console.log(`Plugin wrapper written: ${pluginPath}`)

// ────────────────────────────────────────────────────────────────
// Step 4: Cross-compile with Android Bun runtime via CLI
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 4: Cross-compiling with Android Bun runtime ===")

await $`rm -rf ${OUTPUT_DIR}`
await $`mkdir -p ${OUTPUT_DIR}`

const androidOutputPath = path.join(OUTPUT_DIR, "opencode")

// Build the --define flags for compile-time constants
const migrationsJson = JSON.stringify(migrations)
const parserWorkerPath = bunfsRoot + workerRelativePath

console.log("Running: bun build --compile --compile-executable-path=<android-bun> --target=bun-linux-arm64-android ...")

// NOTE: Bun.$ tagged template doesn't handle complex escaping with \'
// and line continuations well. Use Bun.spawnSync with explicit array.
const buildArgs = [
  "bun", "build", "--compile",
  `--compile-executable-path=${ANDROID_BUN}`,
  "--target=bun-linux-arm64-android",
  `--plugin=${pluginFileName}`,
  "--conditions=browser",
  `--tsconfig=./tsconfig.json`,
  `--outfile=${androidOutputPath}`,
  `--define=OPENCODE_VERSION=${JSON.stringify(VERSION)}`,
  `--define=OPENCODE_MIGRATIONS=${migrationsJson}`,
  `--define=OTUI_TREE_SITTER_WORKER_PATH=${JSON.stringify(parserWorkerPath)}`,
  `--define=OPENCODE_WORKER_PATH=${JSON.stringify(workerPath)}`,
  `--define=OPENCODE_CHANNEL=${JSON.stringify(CHANNEL)}`,
  `--define=OPENCODE_LIBC=${JSON.stringify("")}`,
  "./src/index.ts",
  parserWorkerResolved,
  workerPath,
]

console.log("Build command: bun build --compile ...")
const proc = Bun.spawnSync(buildArgs, {
  cwd: opencodePkgDir,
  stdio: ["inherit", "inherit", "inherit"],
  env: {
    ...process.env,
    // Ensure Bun uses the correct cache for target runtime discovery
    HOME: process.env.HOME || os.homedir(),
  },
})

if (proc.exitCode !== 0) {
  console.error(`Build failed with exit code ${proc.exitCode}`)
  process.exit(proc.exitCode ?? 1)
}

console.log(`\nCross-compile output: ${androidOutputPath}`)

// ────────────────────────────────────────────────────────────────
// Step 5: Verify the binary
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 5: Verifying binary ===")

if (!fs.existsSync(androidOutputPath)) {
  console.error("ERROR: OpenCode binary not found at", androidOutputPath)
  process.exit(1)
}

const stat = fs.statSync(androidOutputPath)
console.log(`Size: ${(stat.size / 1024 / 1024).toFixed(1)} MB`)

// Check ELF header
const header = new Uint8Array(await Bun.file(androidOutputPath).slice(0, 64).arrayBuffer())
const elfMagic = String.fromCharCode(header[0], header[1], header[2], header[3])
console.log(`ELF magic: ${elfMagic === "\x7fELF" ? "OK" : "INVALID"}`)

// Check machine type (0xB7 = AArch64)
const machine = header[18] | (header[19] << 8)
const machineStr = machine === 0xB7 ? "AArch64" : machine === 0x3E ? "x86_64" : `Unknown (0x${machine.toString(16)})`
console.log(`Architecture: ${machineStr}`)

if (machine !== 0xB7) {
  console.error(`ERROR: Expected AArch64 (0xB7), got ${machineStr}`)
  process.exit(1)
}

console.log("Binary verification: OK")

// ────────────────────────────────────────────────────────────────
// Step 6: Cleanup
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 6: Cleanup ===")
try {
  await $`rm -f ${pluginPath}`
  console.log("Plugin wrapper removed")
} catch {
  // non-fatal
}

console.log("\n=== Build complete! ===")
console.log(`Output: ${androidOutputPath}`)
