#!/usr/bin/env bun
/**
 * Build OpenCode for Android (aarch64)
 *
 * This script:
 * 1. Generates the models-snapshot.js
 * 2. Loads migrations
 * 3. Bundles + compiles OpenCode for HOST using Bun.build() API:
 *      Bun.build({compile: {outfile: "opencode-host"}}) → x86_64 standalone
 * 4. Reads the .bun ELF section to extract the module graph
 * 5. Raw-appends module graph to Android Bun binary (no ELF modification)
 *
 * The raw append approach is required because --compile-executable-path
 * uses elf.zig:writeBunSection() which corrupts Android ARM64 ELF binaries.
 * The Android Bun's fromExecutable() fallback (patched) finds the module
 * graph via the \n---- Bun! ----\n trailer at the end of the file.
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"

// These are set by the build-opencode.sh wrapper script
const OPENCODE_DIR = process.env.OPENCODE_DIR || (() => { throw new Error("OPENCODE_DIR env var not set") })()
const ANDROID_BUN = process.env.ANDROID_BUN || (() => { throw new Error("ANDROID_BUN env var not set") })()
const OUTPUT_DIR = process.env.OUTPUT_DIR || (() => { throw new Error("OUTPUT_DIR env var not set") })()

// Validate Android bun exists
if (!fs.existsSync(ANDROID_BUN)) {
  console.error("Android bun binary not found at:", ANDROID_BUN)
  process.exit(1)
}

const opencodePkgDir = path.join(OPENCODE_DIR, "packages/opencode")
process.chdir(opencodePkgDir)

const VERSION = process.env.OPENCODE_VERSION || "1.3.13"
const CHANNEL = process.env.OPENCODE_CHANNEL || "latest"

console.log(`Building OpenCode v${VERSION} (channel: ${CHANNEL}) for Android aarch64`)

// ────────────────────────────────────────────────────────────────
// Step 1: Generate models-snapshot.js
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 1: Generating models-snapshot.js ===")
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
let modelsData: string = ""
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else {
  console.log(`Fetching from ${modelsUrl}/api.json ...`)
  let fetchErr: Error | null = null
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const resp = await fetch(`${modelsUrl}/api.json`, { signal: AbortSignal.timeout(15000) })
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
      modelsData = await resp.text()
      fetchErr = null
      break
    } catch (err: any) {
      fetchErr = err
      console.error(`  Attempt ${attempt}/3 failed: ${err.message}`)
      if (attempt < 3) await new Promise(r => setTimeout(r, 2000 * attempt))
    }
  }
  if (fetchErr) {
    console.error(`ERROR: Failed to fetch models after 3 attempts: ${fetchErr.message}`)
    process.exit(1)
  }
}
await Bun.write(
  path.join(opencodePkgDir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(opencodePkgDir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// ────────────────────────────────────────────────────────────────
// Step 2: Load migrations
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 2: Loading migrations ===")
const migrationDirs = (
  await fs.promises.readdir(path.join(OPENCODE_DIR, "packages/opencode/migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(OPENCODE_DIR, "packages/opencode/migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// ────────────────────────────────────────────────────────────────
// Step 3: Resolve worker paths
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 3: Resolving worker paths ===")

let parserWorkerResolved: string
try {
  parserWorkerResolved = require.resolve("@opentui/core/parser.worker")
} catch {
  parserWorkerResolved = path.resolve(OPENCODE_DIR, "node_modules/@opentui/core/src/lib/tree-sitter/parser.worker.ts")
}
console.log(`Parser worker: ${parserWorkerResolved}`)

const workerPath = "./src/cli/tui/worker.ts"
const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(OPENCODE_DIR, parserWorkerResolved).replaceAll("\\", "/")
const parserWorkerPath = bunfsRoot + workerRelativePath

// ────────────────────────────────────────────────────────────────
// Step 4: Bundle + compile for HOST using Bun.build() API
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 4: Building OpenCode for HOST platform ===")

await $`rm -rf ${OUTPUT_DIR}`
await $`mkdir -p ${OUTPUT_DIR}`

const migrationsJson = JSON.stringify(migrations)
const hostBinaryPath = path.join(OUTPUT_DIR, "opencode-host")

// Bun.build() with compile uses the JS API which handles /\$bunfs/root/
// paths correctly and includes workers via entrypoints + defines.
const plugin = createSolidTransformPlugin()

const result = await Bun.build({
  conditions: ["browser"],
  tsconfig: "./tsconfig.json",
  plugins: [plugin],
  compile: {
    outfile: hostBinaryPath,
    execArgv: [`--user-agent=opencode/${VERSION}`, "--use-system-ca", "--"],
  },
  entrypoints: ["./src/index.ts", parserWorkerResolved, workerPath],
  define: {
    OPENCODE_VERSION: `'${VERSION}'`,
    OPENCODE_MIGRATIONS: migrationsJson,
    OTUI_TREE_SITTER_WORKER_PATH: `'${parserWorkerPath}'`,
    OPENCODE_WORKER_PATH: `'${workerPath}'`,
    OPENCODE_CHANNEL: `'${CHANNEL}'`,
    OPENCODE_LIBC: "''",
  },
})

if (!result.success) {
  console.error("Build failed:", result.logs)
  process.exit(1)
}

console.log(`Host binary: ${hostBinaryPath}`)

// ────────────────────────────────────────────────────────────────
// Step 5: Extract module graph from the .bun ELF section
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 5: Extracting module graph ===")

const TRAILER_STR = "\n---- Bun! ----\n"
const TRAILER_LEN = TRAILER_STR.length
const OFFSETS_SIZE = 32

const hostFileBytes = new Uint8Array(await Bun.file(hostBinaryPath).arrayBuffer())
const utf8decoder = new TextDecoder()

// Scan ELF section headers for ".bun"
const e_shoff = Number(new DataView(hostFileBytes.buffer, 0x28, 8).getBigUint64(0, true))
const e_shentsize = new DataView(hostFileBytes.buffer, 0x3A, 2).getUint16(0, true)
const e_shnum = new DataView(hostFileBytes.buffer, 0x3C, 2).getUint16(0, true)
const e_shstrndx = new DataView(hostFileBytes.buffer, 0x3E, 2).getUint16(0, true)

// Read section name string table
const shstrtabEntry = 0x28 + e_shstrndx * e_shentsize
const shstrtabOffset = Number(new DataView(hostFileBytes.buffer, e_shoff + shstrtabEntry + 0x18, 8).getBigUint64(0, true))
const shstrtabSize = Number(new DataView(hostFileBytes.buffer, e_shoff + shstrtabEntry + 0x20, 8).getBigUint64(0, true))
const shstrtab = hostFileBytes.slice(shstrtabOffset, shstrtabOffset + shstrtabSize)

// Find .bun section
let bunSectionOffset = 0
let bunSectionSize = 0
for (let i = 0; i < e_shnum; i++) {
  const entryOff = e_shoff + i * e_shentsize
  const nameIdx = new DataView(hostFileBytes.buffer, entryOff, 4).getUint32(0, true)
  let nameEnd = nameIdx
  while (nameEnd < shstrtabSize && shstrtab[nameEnd] !== 0) nameEnd++
  const name = utf8decoder.decode(shstrtab.slice(nameIdx, nameEnd))
  if (name === ".bun") {
    bunSectionOffset = Number(new DataView(hostFileBytes.buffer, entryOff + 0x18, 8).getBigUint64(0, true))
    bunSectionSize = Number(new DataView(hostFileBytes.buffer, entryOff + 0x20, 8).getBigUint64(0, true))
    break
  }
}

if (bunSectionSize === 0) {
  console.error("ERROR: .bun section not found in host binary")
  process.exit(1)
}

// Read .bun section content (skip the first 8-byte total_byte_count)
const bunSectionBytes = hostFileBytes.slice(bunSectionOffset, bunSectionOffset + bunSectionSize)
const moduleGraphBytes = bunSectionBytes.subarray(8)
console.log(`Host binary: ${hostFileBytes.length} bytes`)
console.log(`.bun section: offset=0x${bunSectionOffset.toString(16)}, size=${bunSectionBytes.length} bytes`)
console.log(`Module graph extracted: ${moduleGraphBytes.length} bytes`)

// Verify trailer at the right position
const searchBuf = Buffer.from(moduleGraphBytes.buffer, moduleGraphBytes.byteOffset, moduleGraphBytes.length)
const trailerBuf = Buffer.from(TRAILER_STR)
const expectedTrailerStart = moduleGraphBytes.length - TRAILER_LEN
const foundTrailer = searchBuf.compare(trailerBuf, 0, TRAILER_LEN, expectedTrailerStart, moduleGraphBytes.length) === 0

if (!foundTrailer) {
  console.error("ERROR: Module graph trailer not found in .bun section")
  process.exit(1)
}

// Parse module graph offsets for undici patching
const mgBuf = Buffer.from(moduleGraphBytes)
const mgTrailerBuf = Buffer.from(TRAILER_STR)
const trailerPosInMg = mgBuf.lastIndexOf(mgTrailerBuf)
if (trailerPosInMg < 0) throw new Error("Trailer not found in module graph!")

const mgOffsetsStart = trailerPosInMg - OFFSETS_SIZE
const modOff = mgBuf.readUInt32LE(mgOffsetsStart + 8)
console.log(`String data region: [0, ${modOff})`)

// ────────────────────────────────────────────────────────────────
// Step 5b: Patch undici reference (Bun <=1.2.x compat)
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 5b: Patching module graph ===")

const undiciPatterns = [
  {
    name: "undici global ref",
    search: Buffer.from('__reExport(exports_Undici, undici)'),
    replace: Buffer.from('__reExport(exports_Undici, Undici)'),
  },
]

let totalPatches = 0
for (const pattern of undiciPatterns) {
  if (pattern.search.length !== pattern.replace.length) {
    console.warn(`  SKIP ${pattern.name}: different lengths (${pattern.search.length} vs ${pattern.replace.length})`)
    continue
  }
  const strDataRegion = mgBuf.slice(0, modOff)
  let searchPos = 0
  let count = 0
  while (true) {
    const pos = strDataRegion.indexOf(pattern.search, searchPos)
    if (pos < 0) break
    pattern.replace.copy(mgBuf, pos)
    count++
    totalPatches++
    searchPos = pos + pattern.search.length
  }
  if (count > 0) {
    console.log(`  ✓ ${pattern.name}: patched ${count} occurrence(s)`)
  }
}

if (totalPatches === 0) {
  console.log("  No undici patterns found in module graph (Bun 1.3.14)")
}

// ────────────────────────────────────────────────────────────────
// Step 6: Create Android standalone binary (raw append)
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 6: Creating Android standalone binary ===")

var finalModuleGraph = mgBuf.slice(0, trailerPosInMg + mgTrailerBuf.length)

const androidBunBytes = new Uint8Array(await Bun.file(ANDROID_BUN).arrayBuffer())
const androidBunSize = androidBunBytes.length
console.log(`Android bun size: ${androidBunSize}`)

// New total_byte_count = android_bun_size + module_graph.length + 8
const newTotalByteCount = androidBunSize + finalModuleGraph.length + 8

// Create the output buffer: [Android bun][module graph + trailer][total_byte_count u64]
const outputSize = androidBunSize + finalModuleGraph.length + 8
const output = new Uint8Array(outputSize)

output.set(androidBunBytes, 0)
output.set(
  new Uint8Array(finalModuleGraph.buffer, finalModuleGraph.byteOffset, finalModuleGraph.length),
  androidBunSize,
)

const totalView = new DataView(output.buffer, outputSize - 8, 8)
totalView.setUint32(0, newTotalByteCount & 0xFFFFFFFF, true)
totalView.setUint32(4, Math.floor(newTotalByteCount / 0x100000000), true)

const androidOutputPath = path.join(OUTPUT_DIR, "opencode")
await Bun.write(androidOutputPath, output)
fs.chmodSync(androidOutputPath, 0o755)

console.log(`\nAndroid standalone binary: ${androidOutputPath}`)
console.log(`Size: ${(outputSize / 1024 / 1024).toFixed(1)} MB`)

// ────────────────────────────────────────────────────────────────
// Step 7: Verify the binary
// ────────────────────────────────────────────────────────────────
console.log("\n=== Step 7: Verifying binary ===")

const verifyBytes = new Uint8Array(await Bun.file(androidOutputPath).arrayBuffer())
const verifyView = new DataView(verifyBytes.buffer, verifyBytes.length - 8, 8)
const verifyTotal = verifyView.getUint32(0, true) + verifyView.getUint32(4, true) * 0x100000000
console.log(`Verification: total_byte_count=${verifyTotal}, file_size=${verifyBytes.length}, match=${verifyTotal === verifyBytes.length}`)

const elfMagic = String.fromCharCode(verifyBytes[0], verifyBytes[1], verifyBytes[2], verifyBytes[3])
console.log(`ELF magic: ${elfMagic === "\x7fELF" ? "OK" : "INVALID"}`)

const machine = verifyBytes[18] | (verifyBytes[19] << 8)
if (machine !== 0xB7) {
  console.error(`ERROR: Expected AArch64 (0xB7), got ${machine === 0x3E ? "x86_64" : `0x${machine.toString(16)}`}`)
  process.exit(1)
}
console.log("Architecture: AArch64 OK")

// ────────────────────────────────────────────────────────────────
// Done
// ────────────────────────────────────────────────────────────────
console.log("\n=== Build complete! ===")
console.log(`Output: ${androidOutputPath}`)
